### ISSUE TITLE
Use "gatsby new" for quick start

### ISSUE THREAD

**Issue by KyleAMathews** [cpinnix/verious#1]
Hey! This is an awesome initiative! Want to add it to the starters list on gatsbyjs? Also, since this is a starter, you could just instruct people to install gatsby-cli and use that.

**Comment by cpinnix** [comment]
@KyleAMathews Will do! Sorry it took so long to get back.

**Comment by cpinnix** [comment]
@KyleAMathews Pull request out to settle this issue. https://github.com/gatsbyjs/gatsby/pull/3543 Cheers!
